import DrawerRoot from './drawer.svelte'
import { createHandle } from '../../internal/overlay-handle.svelte'

export const Drawer = Object.assign(DrawerRoot, { createHandle })
export { default as DrawerProvider } from './drawer-provider.svelte'
export { default as DrawerIndent } from './drawer-indent.svelte'
export { default as DrawerIndentBackground } from './drawer-indent-background.svelte'
export { default as DrawerTrigger } from './drawer-trigger.svelte'
export { default as DrawerContent } from './drawer-content.svelte'
export { default as DrawerHeader } from './drawer-header.svelte'
export { default as DrawerTitle } from './drawer-title.svelte'
export { default as DrawerDescription } from './drawer-description.svelte'
export { default as DrawerBody } from './drawer-body.svelte'
export { default as DrawerFooter } from './drawer-footer.svelte'
export { default as DrawerClose } from './drawer-close.svelte'
export type { OverlayHandle as DrawerHandle } from '../../internal/overlay-handle.svelte'
export type { DrawerSide, DrawerSnapPoint } from './drawer-context'
export type { DrawerBodyProps } from './drawer-body.svelte'
export type { DrawerCloseProps } from './drawer-close.svelte'
export type { DrawerContentProps } from './drawer-content.svelte'
export type { DrawerDescriptionProps } from './drawer-description.svelte'
export type { DrawerFooterProps } from './drawer-footer.svelte'
export type { DrawerHeaderProps } from './drawer-header.svelte'
export type { DrawerIndentBackgroundProps } from './drawer-indent-background.svelte'
export type { DrawerIndentProps } from './drawer-indent.svelte'
export type { DrawerProviderProps } from './drawer-provider.svelte'
export type { DrawerTitleProps } from './drawer-title.svelte'
export type { DrawerTriggerProps } from './drawer-trigger.svelte'
export type { DrawerProps } from './drawer.svelte'
