import tseslint from 'typescript-eslint'
import svelte from 'eslint-plugin-svelte'
import svelteConfig from './svelte.config.js'

export default tseslint.config(
  {
    ignores: [
      'dist/**',
      'node_modules/**',
      '*.config.mjs',
      '*.config.js',
      'scripts/**',
      '**/*.test.ts',
      '**/*.test-host.svelte',
      'src/test/**',
    ],
  },
  ...svelte.configs['flat/recommended'],
  {
    files: ['**/*.svelte', '**/*.svelte.ts', '**/*.svelte.js'],
    languageOptions: {
      parserOptions: {
        parser: tseslint.parser,
        extraFileExtensions: ['.svelte'],
        svelteConfig,
      },
    },
  },
  {
    files: ['src/providers/theme-provider/**/*.svelte'],
    rules: {
      // Inline no-flash theme script. The string is generated by getThemeScript, not user input.
      'svelte/no-at-html-tags': 'off',
    },
  },
  {
    files: ['src/**/*.ts'],
    ignores: ['**/*.svelte.ts'],
    languageOptions: {
      parser: tseslint.parser,
    },
  },
)
