export { default as Tabs } from './tabs.svelte'
export { default as TabsList } from './tabs-list.svelte'
export { default as TabsTrigger } from './tabs-trigger.svelte'
export { default as TabsContent } from './tabs-content.svelte'
export type { TabsProps } from './tabs.svelte'
export type { TabsListProps } from './tabs-list.svelte'
export type { TabsTriggerProps } from './tabs-trigger.svelte'
export type { TabsContentProps } from './tabs-content.svelte'
