export { default as Collapsible } from './collapsible.svelte'
export { default as CollapsibleTrigger } from './collapsible-trigger.svelte'
export { default as CollapsibleContent } from './collapsible-content.svelte'
export type { CollapsibleContentProps } from './collapsible-content.svelte'
export type { CollapsibleTriggerProps } from './collapsible-trigger.svelte'
export type { CollapsibleProps } from './collapsible.svelte'
