#!/usr/bin/env node
// Regenerate two artifacts from the file system, in lockstep:
//   1. package.json "exports" map - per-entry subpaths
//   2. src/index.ts barrel       - root re-exports
//
// Source of truth: four sibling namespace directories under src/.
//   components/<name>/  → "./<name>"
//   lib/<name>          → "./<name>"
//   hooks/<name>        → "./hooks/<name>"
//   providers/<name>    → "./providers/<name>"
//
// Each entry is a folder. Prefer index.ts when present so a folder can expose
// a .svelte component plus variants/types without leaking internals.

import { readdirSync, readFileSync, writeFileSync, existsSync } from 'node:fs'
import { join, dirname, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'

const __dirname = dirname(fileURLToPath(import.meta.url))
const PKG_DIR = resolve(__dirname, '..')
const SRC_DIR = join(PKG_DIR, 'src')
const PKG_PATH = join(PKG_DIR, 'package.json')
const BARREL_PATH = join(SRC_DIR, 'index.ts')

const NAMESPACES = [
  { dir: 'components', subpathPrefix: '' },
  { dir: 'lib', subpathPrefix: '' },
  { dir: 'hooks', subpathPrefix: 'hooks/' },
  { dir: 'providers', subpathPrefix: 'providers/' },
]

const BARREL_BANNER =
  '// Auto-generated by scripts/sync-exports.mjs from src/{components,lib,hooks,providers}/*.\n' +
  '// Do not edit by hand - your changes will be overwritten on the next build.\n\n'

function hasAny(folder, names) {
  return names.some((n) => existsSync(join(folder, n)))
}

function resolveEntry(namespaceDir, name) {
  const nsDir = join(SRC_DIR, namespaceDir)
  const folder = join(nsDir, name)
  if (existsSync(folder)) {
    if (hasAny(folder, ['index.ts', 'index.js'])) return { importPath: `${name}/index`, kind: 'ts' }
    if (existsSync(join(folder, `${name}.svelte`))) return { importPath: `${name}/${name}`, kind: 'svelte' }
    if (hasAny(folder, [`${name}.ts`, `${name}.js`])) return { importPath: `${name}/${name}`, kind: 'ts' }
  }
  if (existsSync(join(nsDir, `${name}.svelte`))) return { importPath: name, kind: 'svelte' }
  if (hasAny(nsDir, [`${name}.ts`, `${name}.js`])) return { importPath: name, kind: 'ts' }
  return null
}

const ENTRY_FILE_RE = /\.(tsx?|svelte)$/
const TEST_FILE_RE = /\.test\.(tsx?)$/

function listEntries(namespaceDir) {
  const dir = join(SRC_DIR, namespaceDir)
  if (!existsSync(dir)) return []
  const names = new Set()
  for (const e of readdirSync(dir, { withFileTypes: true })) {
    if (e.isDirectory()) {
      names.add(e.name)
    } else if (e.isFile() && ENTRY_FILE_RE.test(e.name) && !TEST_FILE_RE.test(e.name)) {
      names.add(e.name.replace(ENTRY_FILE_RE, ''))
    }
  }
  return [...names]
    .map((name) => {
      const resolved = resolveEntry(namespaceDir, name)
      return resolved ? { name, ...resolved } : null
    })
    .filter(Boolean)
    .sort((a, b) => a.name.localeCompare(b.name))
}

function collectAll() {
  return NAMESPACES.map(({ dir, subpathPrefix }) => ({
    dir,
    subpathPrefix,
    entries: listEntries(dir),
  }))
}

function svelteExport(distPath, kind) {
  if (kind === 'svelte') {
    return {
      types: `./dist/${distPath}.svelte.d.ts`,
      svelte: `./dist/${distPath}.svelte`,
      default: `./dist/${distPath}.svelte`,
    }
  }
  return {
    types: `./dist/${distPath}.d.ts`,
    svelte: `./dist/${distPath}.js`,
    default: `./dist/${distPath}.js`,
  }
}

function buildExports(namespaces) {
  const exports = {
    '.': {
      types: './dist/index.d.ts',
      svelte: './dist/index.js',
      default: './dist/index.js',
    },
  }
  for (const { dir, subpathPrefix, entries } of namespaces) {
    for (const { name, importPath, kind } of entries) {
      exports[`./${subpathPrefix}${name}`] = svelteExport(`${dir}/${importPath}`, kind)
    }
  }
  exports['./styles.css'] = './styles.css'
  exports['./css'] = './appica.css'
  exports['./package.json'] = './package.json'
  return exports
}

function buildBarrel(namespaces) {
  const lines = []
  for (const { dir, entries } of namespaces) {
    for (const { importPath, kind } of entries) {
      const ext = kind === 'svelte' ? '.svelte' : ''
      lines.push(`export * from './${dir}/${importPath}${ext}'`)
    }
  }
  return BARREL_BANNER + lines.join('\n') + '\n'
}

function summarize(namespaces) {
  const parts = namespaces
    .filter((n) => n.entries.length > 0)
    .map((n) => `${n.entries.length} ${n.dir}: ${n.entries.map((e) => e.name).join(', ')}`)
  return parts.length > 0 ? parts.join(' | ') : 'no entries'
}

function main() {
  const check = process.argv.includes('--check')
  const namespaces = collectAll()
  const updates = []

  const pkg = JSON.parse(readFileSync(PKG_PATH, 'utf8'))
  const nextExports = buildExports(namespaces)
  if (JSON.stringify(pkg.exports) !== JSON.stringify(nextExports)) {
    if (!check) {
      pkg.exports = nextExports
      writeFileSync(PKG_PATH, JSON.stringify(pkg, null, 2) + '\n')
    }
    updates.push('package.json:exports')
  }

  const nextBarrel = buildBarrel(namespaces)
  const currentBarrel = existsSync(BARREL_PATH) ? readFileSync(BARREL_PATH, 'utf8') : ''
  if (currentBarrel !== nextBarrel) {
    if (!check) writeFileSync(BARREL_PATH, nextBarrel)
    updates.push('src/index.ts')
  }

  const summary = summarize(namespaces)
  if (updates.length === 0) {
    console.log(`✓ in sync (${summary})`)
  } else if (check) {
    console.error(`✗ out of sync: ${updates.join(' + ')} - run \`pnpm sync-exports\` (${summary})`)
    process.exit(1)
  } else {
    console.log(`✓ regenerated ${updates.join(' + ')} (${summary})`)
  }
}

main()
