export { default as Table } from './table.svelte'
export { default as TableCaption } from './table-caption.svelte'
export { default as TableHeader } from './table-header.svelte'
export { default as TableBody } from './table-body.svelte'
export { default as TableRow } from './table-row.svelte'
export { default as TableHead } from './table-head.svelte'
export { default as TableCell } from './table-cell.svelte'
export type { TableProps } from './table.svelte'
export type { TableCaptionProps } from './table-caption.svelte'
export type { TableHeaderProps } from './table-header.svelte'
export type { TableBodyProps } from './table-body.svelte'
export type { TableRowProps } from './table-row.svelte'
export type { TableHeadProps } from './table-head.svelte'
export type { TableCellProps } from './table-cell.svelte'
