import DialogRoot from './dialog.svelte'
import { createHandle } from '../../internal/overlay-handle.svelte'

export const Dialog = Object.assign(DialogRoot, { createHandle })
export { default as DialogTrigger } from './dialog-trigger.svelte'
export { default as DialogContent } from './dialog-content.svelte'
export { default as DialogHeader } from './dialog-header.svelte'
export { default as DialogTitle } from './dialog-title.svelte'
export { default as DialogDescription } from './dialog-description.svelte'
export { default as DialogBody } from './dialog-body.svelte'
export { default as DialogFooter } from './dialog-footer.svelte'
export { default as DialogClose } from './dialog-close.svelte'
export type { OverlayHandle as DialogHandle } from '../../internal/overlay-handle.svelte'
export type { DialogBodyProps } from './dialog-body.svelte'
export type { DialogCloseProps } from './dialog-close.svelte'
export type { DialogContentProps } from './dialog-content.svelte'
export type { DialogDescriptionProps } from './dialog-description.svelte'
export type { DialogFooterProps } from './dialog-footer.svelte'
export type { DialogHeaderProps } from './dialog-header.svelte'
export type { DialogTitleProps } from './dialog-title.svelte'
export type { DialogTriggerProps } from './dialog-trigger.svelte'
export type { DialogProps } from './dialog.svelte'
